apiVersion: v1
kind: ServiceAccount
metadata:
  name: preconversion-sa
  namespace: preconversion
  annotations:
    # Workload Identity mapping (replace with real GCP SA)
    iam.gke.io/gcp-service-account: preconversion-runtime@your-gcp-project.iam.gserviceaccount.com

